### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by menthy-wu** [acm-ucr/asme-website#2]
- src\components\Landing.jsx
- use react icon [FaGear](https://react-icons.github.io/react-icons/icons?name=fa6) for the gear
![image](https://github.com/acm-ucr/asme-website/assets/73259022/06c95a4d-03e8-4db5-a2e7-ad43bc5bde66)

**Comment by NovaSagittarii** [comment]
react-icons/fa6 doesnt even exist :sob:

![image](https://github.com/acm-ucr/asme-website/assets/12877445/5c97e455-67d9-42f1-882d-7251d0505707)

**Comment by NovaSagittarii** [comment]
u need to bump react-icons to ^4.10.1 :moyai:

**Comment by menthy-wu** [comment]
Ah I see. Can you upgrade it 🥺

**Comment by menthy-wu** [comment]
nvm I did it
