### ISSUE TITLE
Join Us Card Hover

### ISSUE THREAD

**Issue by menthy-wu** [acm-ucr/asme-website#61]
- make the text the same color as the background
- you will need to add another attribute in join cards as textColor
![image](https://github.com/acm-ucr/asme-website/assets/73259022/5d09b00f-cc9e-463a-96f5-03874945423a)

**Comment by NovaSagittarii** [comment]
tailwind doesnt like it when you try concatenating strings to make a new class (`hover:` + `text-color`) and `textColor: hover:!text-color...` (why is textColor as a hover??) looks weird so i just had a separate color mapping
