### ISSUE TITLE
mobile responsive for header

### ISSUE THREAD

**Issue by menthy-wu** [acm-ucr/asme-website#65]
![image](https://github.com/acm-ucr/asme-website/assets/73259022/a411afb4-e8bc-4486-81ac-c3b69ed3872f)

**Comment by NovaSagittarii** [comment]
funny things happen cuz the images are too wide 😔 
![image](https://github.com/acm-ucr/asme-website/assets/12877445/2bbff271-066f-4862-879c-9fdce00d2499)
