### ISSUE TITLE
Join Animcation

### ISSUE THREAD

**Issue by menthy-wu** [acm-ucr/asme-website#86]
<img width="1512" alt="image" src="https://github.com/acm-ucr/asme-website/assets/73259022/1de7b6e7-1d00-4c74-af84-31783f23b376">

**Comment by NovaSagittarii** [comment]
![image](https://github.com/acm-ucr/asme-website/assets/12877445/3b12d3b4-d7bd-4446-9af7-a02a8e8bd91c)
